name: serverpod_project_flutter
description: A new Flutter project with Serverpod.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'
dependencies:
  cached_network_image: ^3.4.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.5.0
  serverpod_flutter: 2.9.1
  serverpod_project_client:
    path: ../serverpod_project_client
  shared_preferences: ^2.3.1
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/animations/